apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cepg-82210669-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cepg-82210669-rwmany
  resources:
    requests:
      storage: 1Gi
