apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-app-pvc
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-app-pvc-once
  resources:
    requests:
      storage: 10Gi
